Repository apirator/apirator, pull requests merged in 2020-02, with the labels that each got.

#2 support service type
  deploy/crds/apirator.io_apimocks_crd.yaml
  deploy/crds/apirator.io_v1alpha1_apimock_cr.yaml
  pkg/apis/apirator/v1alpha1/apimock_types.go
  pkg/apis/apirator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/apimock/service.go
Labels: enhancement

#5 Create LICENSE
  LICENSE
Labels: documentation

#9 add license headers in files
  go.mod
  go.sum
  pkg/apis/addtoscheme_apirator_v1alpha1.go
  pkg/apis/apirator/group.go
  pkg/apis/apirator/v1alpha1/apimock_types.go
  pkg/apis/apirator/v1alpha1/doc.go
  pkg/apis/apirator/v1alpha1/register.go
  pkg/apis/apirator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apis.go
  pkg/controller/add_apimock.go
  pkg/controller/apimock/apimock_controller.go
  pkg/controller/apimock/configmap.go
  pkg/controller/apimock/deployment.go
  pkg/controller/apimock/pod.go
  pkg/controller/apimock/service.go
  pkg/controller/apimock/status.go
  pkg/controller/controller.go
  pkg/controller/k8s/util/labels/labels.go
  pkg/controller/k8s/util/owner/owner.go
Labels: documentation

#14 Feature/validate oas
  deploy/crds/apirator.io_apimocks_crd.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/apirator/v1alpha1/apimock_types.go
  pkg/controller/apimock/apimock_controller.go
  pkg/controller/apimock/status.go
  pkg/controller/oas/oas_validator.go
Labels: enhancement

#16 Documentation/licence badge
  README.md
Labels: documentation

#18 Feature/add doc container
  README.md
  deploy/crds/apirator.io_apimocks_crd.yaml
  deploy/crds/apirator.io_v1alpha1_apimock_cr.yaml
  deploy/operator.yaml
  development-deploy.sh
  go.mod
  logs.sh
  pkg/apis/apirator/v1alpha1/apimock_types.go
  pkg/apis/apirator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/apimock/apimock_controller.go
  pkg/controller/apimock/configmap.go
  pkg/controller/apimock/pod.go
  pkg/controller/apimock/service.go
Labels: enhancement

#22 Using StatusWriter to update the subresource status
  deploy/crds/apirator.io_apimocks_crd.yaml
  pkg/apis/apirator/v1alpha1/apimock_types.go
  pkg/controller/apimock/status.go
Labels: bug

#21 add doc port on service object
  pkg/controller/apimock/service.go
Labels: enhancement
